[project]
name = "glass-rpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "msgpack>=1.1.0",
]

[tool.ruff]
line-length = 100